### ISSUE TITLE
Defects4j prepare test data

### ISSUE THREAD

**Issue by QingyuanLi1211** [lin-tan/CURE#16]

**Comment by QingyuanLi1211** [comment]
Dear author, how did you get the exact location （line number） of the buggy line in each method when preparing the test data on d4j? Arguments of function prepare_cure_input start_line and end_line need line number information. Is it possible to share a copy of the source code?

**Comment by QingyuanLi1211** [comment]
I got understand every scripts in CURE after reading and using CoCoNut, SequenceR, Recoder, RewardRepair NPR tools. If anyone has problem on the project, u can ask me for help~

**Comment by zombieQQ** [comment]
你好，我有一个问题就是在测试其他数据的时候，比如作者提供的 testcase，我使用了 prepare_test_data.py 文件去处理测试的文件，但是在进行生成补丁的时候会出现类似![image](https://github.com/lin-tan/CURE/assets/47177498/5feca915-c354-4473-bef7-7b43495defae)这种 txt 文件，请问是什么原因呢？非常感谢
